// The shared UI kit: one set of tokens, one set of primitives, one motion
// vocabulary, for every app in /apps.
//
// Apps do NOT link this file — they carry a copy of it inline, between the
// sentinel comments below, exactly the way each one carries its own copy of the
// language runtime. That keeps the single-file rule intact and keeps
// `open apps/<slug>/index.html` from a bare clone working. This module is the
// source of truth; `node scripts/build.mjs --sync-ui` writes it into every app,
// and a normal build fails if an app's copy has drifted.
//
//   scripts/ui.mjs  --sync-ui-->  apps/*/index.html  --build-->  dist/
//
// Change a token here, run --sync-ui, commit. Never hand-edit the block inside
// an app: the next build will tell you it is stale, and the next sync will
// overwrite it.

import { hueFor } from './icon.mjs';
import { createHash } from 'node:crypto';

export const UI_OPEN = '/* ==== jnssn-ui: generated by scripts/ui.mjs — do not edit, run `node scripts/build.mjs --sync-ui` ==== */';
export const UI_CLOSE = '/* ==== /jnssn-ui ==== */';

/* ---------- fonts ----------
   One family, not two. Hierarchy comes from weight and optical size, which is
   what a native app does; it also halves the font round-trips on a cold cache,
   and fonts are the single biggest thing standing between a tap on the icon and
   a readable screen on mobile data. */
export const FONT_LINK = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">`;

/* ---------- tokens ----------
   Light is defined on bare :root, dark overrides only the values. A colour
   whose only definition sits inside a media query never applies in the
   un-stamped state, which renders one theme's text on the other theme's ground.

   The accent is derived from the app's hue, the same hue that colours its icon
   and its theme-colour, so a game looks like the tile the player tapped. */
export function tokens(slug) {
  const h = slug == null ? 222 : hueFor(slug);
  return `
:root{
  color-scheme:light dark;
  --h:${h};

  /* surfaces — neutrals carry a slight cool bias so they read as chosen */
  --bg:#F4F5F8; --surface:#FFFFFF; --raised:#FFFFFF; --inset:#EDEFF4;
  --line:#DFE3EC; --line-soft:#EAEDF3;

  /* ink */
  --text:#14161C; --dim:#5C6376; --faint:#8C93A6;

  /* accent, from the app's own hue */
  --accent:hsl(var(--h) 64% 42%);
  --accent-ink:#FFFFFF;
  --accent-wash:hsl(var(--h) 72% 96%);
  --accent-edge:hsl(var(--h) 52% 84%);

  /* semantic — separate from the accent on purpose */
  --pos:hsl(152 58% 32%); --neg:hsl(356 68% 46%);
  --pos-wash:hsl(152 52% 95%); --neg-wash:hsl(356 82% 96%);

  /* elevation. The inner top highlight is what makes a panel read as a
     physical object instead of a flat rectangle; it matters most in dark. */
  --lift:0 1px 2px hsl(var(--h) 24% 12% / .06), 0 4px 14px hsl(var(--h) 24% 12% / .05);
  --lift-hi:0 2px 4px hsl(var(--h) 24% 12% / .08), 0 12px 32px hsl(var(--h) 24% 12% / .10);
  --edge:inset 0 1px 0 hsl(0 0% 100% / .7);

  /* geometry */
  --r-sm:9px; --r:14px; --r-lg:20px; --r-full:999px;
  --tap:48px;

  /* motion. Expo-out for movement, a slight overshoot for presses. Both are
     applied to transform and opacity only, so they stay on the compositor. */
  --fast:130ms; --mid:220ms; --slow:340ms;
  --ease:cubic-bezier(.16,1,.3,1);
  --spring:cubic-bezier(.34,1.42,.64,1);
}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){${DARK}}}
:root[data-theme="dark"]{${DARK}}
`.trim();
}

const DARK = `
  --bg:#0B0C10; --surface:#14161C; --raised:#1A1D25; --inset:#0E1015;
  --line:#262A34; --line-soft:#1E212A;
  --text:#ECEEF3; --dim:#959CAF; --faint:#6B7286;
  --accent:hsl(var(--h) 76% 64%);
  --accent-ink:#0B0C10;
  --accent-wash:hsl(var(--h) 40% 16%);
  --accent-edge:hsl(var(--h) 40% 28%);
  --pos:hsl(152 62% 56%); --neg:hsl(356 92% 70%);
  --pos-wash:hsl(152 36% 14%); --neg-wash:hsl(356 42% 16%);
  --lift:0 1px 2px #0006, 0 6px 18px #0007;
  --lift-hi:0 2px 6px #0007, 0 18px 44px #0009;
  --edge:inset 0 1px 0 hsl(0 0% 100% / .06);
`.trim();

/* ---------- primitives ---------- */
export const UI_CSS = `
*{box-sizing:border-box;margin:0;padding:0}
html{-webkit-text-size-adjust:100%;height:100%}
body{
  font-family:"Instrument Sans",system-ui,-apple-system,"Segoe UI",sans-serif;
  font-size:16px;line-height:1.45;color:var(--text);background:var(--bg);
  min-height:100%;-webkit-tap-highlight-color:transparent;
  text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;
  overscroll-behavior-y:none;
}
.wrap{max-width:480px;margin:0 auto;padding:calc(16px + env(safe-area-inset-top,0px)) 16px calc(28px + env(safe-area-inset-bottom,0px))}
h1,h2,h3{line-height:1.15;text-wrap:balance;font-weight:700;letter-spacing:-.02em}
h1{font-size:28px}
h2{font-size:19px;letter-spacing:-.01em}
h3{font-size:15px}
.num{font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1;letter-spacing:-.02em}
.eyebrow{font-size:11.5px;font-weight:600;letter-spacing:.09em;text-transform:uppercase;color:var(--faint)}
.dim{color:var(--dim)}.faint{color:var(--faint)}
.pos{color:var(--pos)}.neg{color:var(--neg)}
.stack{display:flex;flex-direction:column;gap:10px}
.stack-lg{display:flex;flex-direction:column;gap:22px}
hr{border:0;border-top:1px solid var(--line);margin:18px 0}

/* --- surfaces --------------------------------------------------------- */
.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);box-shadow:var(--lift),var(--edge)}
.card.flat{box-shadow:none}
.card.quiet{background:transparent;box-shadow:none;border-color:var(--line-soft)}
.pad{padding:14px 16px}
.list>*{border-top:1px solid var(--line-soft)}
.list>*:first-child{border-top:0}

.row{display:flex;align-items:center;gap:12px;padding:12px 14px;min-height:var(--tap)}
.grow{min-width:0;flex:1}
/* display:block so these read the same whether the app emits div or span */
.row .title{display:block;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.row .sub{display:block;font-size:13px;color:var(--dim);margin-top:1px}
.row.lead{background:var(--accent-wash)}

/* --- controls ---------------------------------------------------------- */
button,input,select{font:inherit;color:inherit}
.btn{
  display:flex;align-items:center;justify-content:center;gap:8px;width:100%;
  min-height:54px;padding:0 20px;border:1px solid transparent;border-radius:var(--r);
  background:var(--accent);color:var(--accent-ink);font-weight:600;font-size:16.5px;
  letter-spacing:-.01em;cursor:pointer;box-shadow:var(--lift);
  transition:transform var(--fast) var(--spring),opacity var(--fast) linear,background var(--fast) linear;
}
.btn:active:not(:disabled){transform:scale(.972)}
.btn:disabled{opacity:.38;cursor:default;box-shadow:none}
.btn.ghost{background:var(--surface);color:var(--text);border-color:var(--line);box-shadow:var(--lift),var(--edge)}
.btn.quiet{background:transparent;color:var(--dim);border-color:transparent;box-shadow:none;min-height:var(--tap);font-size:15px}
.btn.danger{background:transparent;color:var(--neg);border-color:var(--line);box-shadow:none}
.btn.sm{min-height:40px;font-size:14.5px;padding:0 14px;border-radius:var(--r-full);width:auto}
.btns{display:grid;gap:10px}
.btns.two{grid-template-columns:1fr 1fr}

/* Stepper. The value is the biggest thing in the row because it is the thing
   being read back; the buttons are quiet until touched. */
.stepper{display:flex;align-items:center;gap:2px;flex:none;background:var(--inset);border-radius:var(--r-full);padding:3px}
.stepper button{
  width:44px;height:44px;display:grid;place-items:center;border:0;border-radius:50%;
  background:transparent;color:var(--accent);cursor:pointer;
  transition:transform var(--fast) var(--spring),background var(--fast) linear;
}
.stepper button:active:not(:disabled){transform:scale(.86);background:var(--accent-wash)}
.stepper button:disabled{opacity:.22;cursor:default}
.stepper .val{min-width:40px;text-align:center;font-size:22px;font-weight:700}

.toggle{
  width:52px;height:32px;flex:none;border-radius:var(--r-full);border:0;cursor:pointer;
  background:var(--inset);position:relative;box-shadow:inset 0 0 0 1px var(--line);
  transition:background var(--mid) var(--ease),box-shadow var(--mid) var(--ease);
}
.toggle::after{
  content:"";position:absolute;top:3px;left:3px;width:26px;height:26px;border-radius:50%;
  background:var(--surface);box-shadow:0 1px 3px #0003;
  transition:transform var(--mid) var(--spring);
}
.toggle[aria-pressed="true"]{background:var(--accent);box-shadow:none}
.toggle[aria-pressed="true"]::after{transform:translateX(20px)}

/* Segmented control — the language bar and any 2-3 way choice. */
.seg{display:flex;background:var(--inset);border-radius:var(--r-full);padding:3px;gap:2px;flex:none}
.seg button{
  border:0;background:transparent;color:var(--dim);cursor:pointer;border-radius:var(--r-full);
  padding:7px 13px;min-height:36px;font-size:13px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;
  transition:color var(--fast) linear,background var(--mid) var(--ease);
}
.seg button[aria-pressed="true"]{background:var(--surface);color:var(--text);box-shadow:var(--lift)}

.field{
  width:100%;min-height:var(--tap);padding:12px 14px;border-radius:var(--r-sm);
  border:1px solid var(--line);background:var(--inset);color:var(--text);
  font-size:16px;-webkit-appearance:none;
  transition:border-color var(--fast) linear,background var(--fast) linear;
}
.field::placeholder{color:var(--faint)}
.field:focus{outline:none;border-color:var(--accent);background:var(--surface)}

.chip{
  display:inline-flex;align-items:center;gap:5px;padding:3px 9px;border-radius:var(--r-full);
  background:var(--inset);color:var(--dim);font-size:12.5px;font-weight:600;white-space:nowrap;
}
/* Outlined, not filled. Red/green are reserved for good/bad, and an app whose
   own hue lands in the red band (rikiki is 352) would otherwise have its
   accent chip read as a failure. Semantic colour stays semantic. */
.chip.on{background:transparent;color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent-edge)}
.chip.bad{background:var(--neg-wash);color:var(--neg)}
.chip.good{background:var(--pos-wash);color:var(--pos)}

:where(a,button,input,select,summary):focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:var(--r-sm)}

/* --- progress ----------------------------------------------------------
   Dots, not a bar: a game has a countable number of rounds, and the count is
   information the player wants. Past 14 it falls back to a bar. */
.dots{display:flex;gap:5px;align-items:center;flex-wrap:wrap}
.dots i{width:7px;height:7px;border-radius:50%;background:var(--line);transition:transform var(--mid) var(--spring),background var(--mid) linear}
.dots i.done{background:var(--accent);opacity:.45}
.dots i.now{background:var(--accent);transform:scale(1.62)}
.bar{height:5px;border-radius:var(--r-full);background:var(--line);overflow:hidden}
.bar>i{display:block;height:100%;background:var(--accent);border-radius:inherit;transition:width var(--slow) var(--ease)}

/* --- table -------------------------------------------------------------- */
.scroll{overflow-x:auto;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain}
table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}
th,td{padding:9px 10px;text-align:center;white-space:nowrap;border-top:1px solid var(--line-soft)}
thead th{position:sticky;top:0;background:var(--surface);font-size:13px;font-weight:600;border-top:0;border-bottom:1px solid var(--line);vertical-align:bottom}
tbody th{position:sticky;left:0;background:var(--surface);color:var(--faint);font-size:12.5px;font-weight:500;text-align:left;width:1%}

/* --- feedback ----------------------------------------------------------- */
.empty{padding:26px 18px;text-align:center;color:var(--dim);font-size:14.5px}
#toast{position:fixed;left:0;right:0;bottom:calc(14px + env(safe-area-inset-bottom,0px));display:flex;justify-content:center;pointer-events:none;z-index:40;padding:0 14px}
#toast .t{
  display:flex;align-items:center;gap:14px;max-width:440px;width:100%;
  background:var(--raised);color:var(--text);border:1px solid var(--line);
  border-radius:var(--r);padding:12px 14px;box-shadow:var(--lift-hi),var(--edge);
  pointer-events:auto;font-size:14.5px;
  animation:toast-in var(--slow) var(--ease) both;
}
#toast .t.out{animation:toast-out var(--mid) var(--ease) both}
#toast .t span{flex:1;min-width:0}
#toast .t button{border:0;background:transparent;color:var(--accent);font-weight:700;font-size:14.5px;cursor:pointer;padding:6px 2px;flex:none}
@keyframes toast-in{from{opacity:0;transform:translateY(14px) scale(.97)}to{opacity:1;transform:none}}
@keyframes toast-out{to{opacity:0;transform:translateY(8px) scale(.98)}}

/* --- motion ------------------------------------------------------------- */
@keyframes rise{from{opacity:0;transform:translateY(9px)}to{opacity:1;transform:none}}
.rise{animation:rise var(--slow) var(--ease) both}
.rise:nth-child(2){animation-delay:40ms}
.rise:nth-child(3){animation-delay:80ms}
.rise:nth-child(4){animation-delay:120ms}
.rise:nth-child(5){animation-delay:160ms}
@keyframes bump{50%{transform:scale(1.22)}}
.bump{animation:bump var(--mid) var(--spring)}

/* Cross-screen transitions. Supported browsers animate; the rest just swap. */
::view-transition-old(root){animation:vt-out var(--mid) var(--ease) both}
::view-transition-new(root){animation:vt-in var(--slow) var(--ease) both}
@keyframes vt-out{to{opacity:0;transform:translateY(-6px)}}
@keyframes vt-in{from{opacity:0;transform:translateY(10px)}}

@media (prefers-reduced-motion:reduce){
  *,*::before,*::after{animation-duration:1ms!important;animation-delay:0ms!important;transition-duration:1ms!important}
  ::view-transition-old(root),::view-transition-new(root){animation:none}
}
`.trim();

/* ---------- runtime ----------
   Small on purpose. Everything here is something every app needs and nobody
   should re-derive: a toast with undo, a view swap that animates, and a patch
   helper that updates text in place instead of rebuilding the screen. */
export const UI_JS = `
(function(){
  var reduce = matchMedia('(prefers-reduced-motion: reduce)');

  /* Swap a view with a transition where the browser has one. Safari 18+,
     Chrome 111+; everywhere else the callback simply runs. */
  function swap(fn){
    if(reduce.matches || !document.startViewTransition){ fn(); return; }
    document.startViewTransition(fn);
  }

  /* Update in place. Rebuilding a screen with innerHTML on every tap throws
     away focus, scroll position and screen-reader context, and makes animation
     impossible — so text that changes goes through here instead. */
  function setText(el, v){
    if(!el) return;
    v = String(v);
    if(el.textContent === v) return;
    el.textContent = v;
    if(!reduce.matches){ el.classList.remove('bump'); void el.offsetWidth; el.classList.add('bump'); }
  }
  function setAttr(el, k, v){
    if(!el) return;
    if(v === false || v == null) el.removeAttribute(k);
    else if(el.getAttribute(k) !== String(v)) el.setAttribute(k, v);
  }

  /* One toast at a time, with an optional undo. Undo beats a confirmation
     dialog: it costs one tap instead of two and never blocks the screen. */
  var host, timer, cur;
  function toast(msg, opts){
    opts = opts || {};
    if(!host){ host = document.createElement('div'); host.id = 'toast'; document.body.appendChild(host); }
    clearTimeout(timer);
    host.textContent = '';
    var box = document.createElement('div');
    box.className = 't'; box.setAttribute('role','status');
    var text = document.createElement('span'); text.textContent = msg; box.appendChild(text);
    if(opts.undo){
      var b = document.createElement('button');
      b.type = 'button'; b.textContent = opts.undoLabel || 'Undo';
      b.addEventListener('click', function(){ hide(); opts.undo(); });
      box.appendChild(b);
    }
    host.appendChild(box); cur = box;
    timer = setTimeout(hide, opts.ms || (opts.undo ? 6000 : 3200));
  }
  function hide(){
    clearTimeout(timer);
    if(!cur) return;
    var box = cur; cur = null;
    box.classList.add('out');
    setTimeout(function(){ if(box.parentNode) box.parentNode.removeChild(box); }, 220);
  }

  window.UI = { swap:swap, setText:setText, setAttr:setAttr, toast:toast, hideToast:hide, reduced:function(){ return reduce.matches; } };
})();`.trim();

/* ---------- assembly ---------- */

// The exact block an app carries. Slug-specific only in its hue.
export function uiBlock(slug) {
  return `${UI_OPEN}\n${tokens(slug)}\n${UI_CSS}\n${UI_CLOSE}`;
}

export function uiScriptBlock() {
  return `${UI_OPEN.replace('/*', '//').replace('*/', '').trim()}\n${UI_JS}\n// ==== /jnssn-ui ====`;
}

// Drift check. An app's copy is stale when this does not match what is in the
// file, which is the only thing standing between one design system and five.
export function uiVersion(slug) {
  return createHash('sha256').update(uiBlock(slug) + UI_JS).digest('hex').slice(0, 12);
}
